### PR TITLE
Uploadcare AVIF

### PR DESCRIPTION
**Pull request by KamillaGarifullina**

### CODE REVIEW

**Comment by justinschmitz97** [comment]
Any reason this was closed? Can integrate it this week. We need to cut on some sales language though.

**Comment by KamillaGarifullina** [comment]
> Any reason this was closed? Can integrate it this week. We need to cut on some sales language though.

Sorry, my manager wants to check the text again, I hurried to post it.

**Comment by KamillaGarifullina** [comment]
We checked all details, everything is correct and can be added to the site.

**Comment by justinschmitz97** [comment]
Removed marketing phrases, added meta & performed Grammarly improvements.

**Pull request merged**
